export const categories = {
  accessibility: ["Activity", "AlertTriangle", "Bicycle", "Moon"],
  "accounts & access": ["Airplay", "Search"],
  animals: ["Anchor", "ArrowDownCircle"],
  arrows: [],
  brands: [],
  buildings: [],
  charts: [],
  communication: [],
  connectivity: [],
  cursors: [],
  design: [],
  "coding & development": [],
  devices: [],
  emoji: [],
};
